"""
Phase 5b — Flow Routing & Impact Corridor Generation
=====================================================
Requires:
  - NASADEM_*.tif files downloaded from Google Drive (from step5a)
  - top5_outlets.csv (generated by step5a)
  - pip install pysheds rasterio shapely geopandas

For each top-5 lake:
  1. Load NASADEM GeoTIFF
  2. Fill depressions + resolve flats (critical preprocessing)
  3. Compute D8 flow direction from lake outlet
  4. Trace downstream flow path
  5. Buffer ±750m → impact corridor polygon
  6. Export all corridors as GeoJSON

OUTPUT: flood_corridors.geojson — used in Phase 6
"""

import os
import glob
import numpy as np
import pandas as pd
import geopandas as gpd
import rasterio
from rasterio.transform import rowcol
from shapely.geometry import LineString, MultiLineString, Point, mapping
from shapely.ops import unary_union
import warnings
warnings.filterwarnings("ignore")

# pysheds imports
from pysheds.grid import Grid

# =====================================================
# CONFIG
# =====================================================

OUTLETS_CSV      = "top5_outlets.csv"
DEM_FOLDER       = "."           # folder where NASADEM TIFFs are stored
CORRIDOR_BUFFER  = 750           # metres — impact corridor half-width
MAX_FLOW_CELLS   = 50000         # max cells to trace downstream (safety limit)
OUTPUT_GEOJSON   = "flood_corridors.geojson"

# =====================================================
# HELPER: DEM file for a given GL_ID
# =====================================================

def find_dem(gl_id):
    safe_id = gl_id.replace("/", "_")
    pattern = os.path.join(DEM_FOLDER, f"NASADEM_{safe_id}*.tif")
    matches = glob.glob(pattern)
    if not matches:
        print(f"  WARNING: No DEM found for {gl_id} (pattern: {pattern})")
        return None
    return matches[0]

# =====================================================
# HELPER: Degrees → approximate metres at given latitude
# =====================================================

def deg_to_m(deg, lat):
    """Convert degrees to metres (approximate, for buffering)."""
    lat_rad = np.radians(lat)
    m_per_deg_lat = 111132.92 - 559.82 * np.cos(2 * lat_rad)
    m_per_deg_lon = 111412.84 * np.cos(lat_rad)
    return deg * (m_per_deg_lat + m_per_deg_lon) / 2

def m_to_deg(metres, lat):
    lat_rad    = np.radians(lat)
    m_per_deg  = 111132.92 - 559.82 * np.cos(2 * lat_rad)
    return metres / m_per_deg

# =====================================================
# CORE: Route flow from outlet and extract path
# =====================================================

def route_flow(dem_path, outlet_lon, outlet_lat, gl_id):
    """
    1. Load DEM via pysheds
    2. Fill depressions, resolve flats
    3. Compute D8 flow direction
    4. Accumulation map
    5. Snap outlet to highest accumulation nearby
    6. Trace downstream path
    Returns: list of (lon, lat) tuples or None
    """
    print(f"  Loading DEM: {dem_path}")

    # ── Load ──
    grid = Grid.from_raster(dem_path)
    dem  = grid.read_raster(dem_path)

    print(f"  DEM shape: {dem.shape}, "
          f"bounds: {grid.bbox}")

    # ── Condition DEM ──
    # Step 1: fill pits (single-cell depressions)
    pit_filled = grid.fill_pits(dem)

    # Step 2: fill depressions (larger sinks)
    flooded    = grid.fill_depressions(pit_filled)

    # Step 3: resolve flats (areas of equal elevation)
    inflated   = grid.resolve_flats(flooded)

    # ── D8 Flow Direction ──
    # dirmap: (N, NE, E, SE, S, SW, W, NW)
    dirmap = (64, 128, 1, 2, 4, 8, 16, 32)
    fdir   = grid.flowdir(inflated, dirmap=dirmap)

    # ── Flow Accumulation ──
    acc = grid.accumulation(fdir, dirmap=dirmap)

    # ── Snap outlet to high-accumulation cell ──
    # Search within ~500m radius for the highest accumulation pixel
    snap_radius_deg = m_to_deg(500, outlet_lat)

    try:
        snapped = grid.snap_to_mask(
            acc > np.percentile(acc, 80),
            (outlet_lon, outlet_lat),
            snap_radius_deg
        )
        # snap_to_mask may return arrays or scalars depending on pysheds version
        if hasattr(snapped[0], '__len__'):
            x_snap = float(snapped[0][0])
            y_snap = float(snapped[1][0])
        else:
            x_snap = float(snapped[0])
            y_snap = float(snapped[1])
    except Exception as e:
        print(f"  Snap failed ({e}), using raw outlet coordinates")
        x_snap, y_snap = float(outlet_lon), float(outlet_lat)

    print(f"  Outlet snapped to: ({x_snap:.5f}, {y_snap:.5f})")

    # ── Trace downstream path ──
    try:
        path_lon, path_lat = [], []

        # Walk downstream cell by cell
        # pysheds catchment gives us the upstream mask;
        # for downstream we trace the flow direction manually
        x, y = x_snap, y_snap

        # D8 direction offsets (row, col) for dirmap above
        # 64=N, 128=NE, 1=E, 2=SE, 4=S, 8=SW, 16=W, 32=NW
        dir_offsets = {
            64:  (-1,  0),   # N
            128: (-1,  1),   # NE
            1:   ( 0,  1),   # E
            2:   ( 1,  1),   # SE
            4:   ( 1,  0),   # S
            8:   ( 1, -1),   # SW
            16:  ( 0, -1),   # W
            32:  (-1, -1),   # NW
        }

        with rasterio.open(dem_path) as src:
            transform = src.transform
            nrows, ncols = src.height, src.width

        # Convert outlet lon/lat → row/col
        row, col = rowcol(transform, x, y)
        row, col = int(row), int(col)

        visited = set()
        fdir_arr = np.array(fdir)

        for _ in range(MAX_FLOW_CELLS):
            if (row, col) in visited:
                break
            if row < 0 or row >= nrows or col < 0 or col >= ncols:
                break

            visited.add((row, col))

            # Convert pixel centre → lon/lat
            lon_pt = transform.c + (col + 0.5) * transform.a
            lat_pt = transform.f + (row + 0.5) * transform.e
            path_lon.append(lon_pt)
            path_lat.append(lat_pt)

            # Get flow direction at current cell
            d = int(fdir_arr[row, col])
            if d not in dir_offsets:
                break

            drow, dcol = dir_offsets[d]
            row += drow
            col += dcol

        if len(path_lon) < 2:
            print(f"  WARNING: Flow path too short ({len(path_lon)} cells)")
            return None

        print(f"  Flow path: {len(path_lon)} cells "
              f"(~{len(path_lon)*30/1000:.1f} km)")
        return list(zip(path_lon, path_lat))

    except Exception as e:
        print(f"  ERROR tracing flow path: {e}")
        return None

# =====================================================
# CORE: Build corridor polygon from flow path
# =====================================================

def build_corridor(path_coords, outlet_lat, buffer_m=CORRIDOR_BUFFER):
    """
    Buffer the flow path line by buffer_m metres.
    Returns a Shapely polygon in EPSG:4326.
    """
    line        = LineString(path_coords)
    buffer_deg  = m_to_deg(buffer_m, outlet_lat)
    corridor    = line.buffer(buffer_deg, cap_style=2, join_style=2)
    return corridor

# =====================================================
# MAIN
# =====================================================

outlets = pd.read_csv(OUTLETS_CSV)
print(f"Processing {len(outlets)} lakes for flow routing...\n")

corridors = []

for _, row in outlets.iterrows():
    gl_id      = row["GL_ID"]
    outlet_lon = row["outlet_lon"]
    outlet_lat = row["outlet_lat"]

    print(f"\n── {gl_id} ──")

    dem_path = find_dem(gl_id)
    if dem_path is None:
        print(f"  Skipping — DEM not found.")
        continue

    # Route flow
    path = route_flow(dem_path, outlet_lon, outlet_lat, gl_id)
    if path is None:
        print(f"  Skipping — routing failed.")
        continue

    # Build corridor
    corridor = build_corridor(path, outlet_lat)

    corridors.append({
        "GL_ID":       gl_id,
        "Basin":       row["Basin"],
        "Sub_Basin":   row.get("Sub_Basin", ""),
        "z_score":     row["z_score"],
        "risk_class":  row["risk_class"],
        "path_cells":  len(path),
        "path_km":     round(len(path) * 30 / 1000, 1),
        "geometry":    corridor
    })
    print(f"  Corridor created: {round(len(path)*30/1000, 1)} km path, "
          f"{corridor.area * 1e10:.1f} km² area (approx)")

# =====================================================
# EXPORT
# =====================================================

if not corridors:
    print("\nNo corridors generated. Check DEM files are in the right folder.")
else:
    gdf_corridors = gpd.GeoDataFrame(corridors, crs="EPSG:4326")
    gdf_corridors.to_file(OUTPUT_GEOJSON, driver="GeoJSON")
    print(f"\nSaved: {OUTPUT_GEOJSON}  ({len(corridors)} corridors)")
    print(gdf_corridors[["GL_ID", "risk_class", "path_km"]].to_string(index=False))

print("\nPhase 5 complete. Run step6_exposure.py next.")