"""
Phase 8 — Real-Time GLOF Risk Dashboard
========================================
Streamlit app that reads pipeline outputs and displays a live dashboard.

Install:
    pip install streamlit folium streamlit-folium plotly pandas geopandas

Run:
    streamlit run step8_dashboard.py

Auto-refresh: the app checks file modification times and reloads
when pipeline outputs are updated — simulating near-real-time monitoring.

Files it reads (all generated by previous phases):
    - final_risk_scores.csv       (Phase 7)
    - agricultural_exposure.csv   (Phase 6)
    - lake_risk_output.csv        (Phase 3)
    - final_risk_map.geojson      (Phase 7) — optional
    - flood_corridors.geojson     (Phase 5) — optional
    - filtered_glacial_lakes.geojson (Phase 1)
"""

import streamlit as st
import pandas as pd
import numpy as np
import geopandas as gpd
import folium
from streamlit_folium import st_folium
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import os
import json
from datetime import datetime

# =====================================================
# PAGE CONFIG
# =====================================================

st.set_page_config(
    page_title  = "GLOF Risk Monitor — Nepal Himalaya",
    page_icon   = "🏔️",
    layout      = "wide",
    initial_sidebar_state = "expanded"
)

# =====================================================
# STYLING
# =====================================================

st.markdown("""
<style>
    .main { background-color: #0f1923; }
    .stMetric { background-color: #1a2634; border-radius: 8px; padding: 10px; }
    .risk-critical { color: #e74c3c; font-weight: bold; }
    .risk-high     { color: #e67e22; font-weight: bold; }
    .risk-moderate { color: #f1c40f; font-weight: bold; }
    .risk-low      { color: #2ecc71; font-weight: bold; }
    div[data-testid="metric-container"] {
        background-color: #1a2634;
        border: 1px solid #2c3e50;
        border-radius: 8px;
        padding: 12px;
    }
</style>
""", unsafe_allow_html=True)

# =====================================================
# DATA LOADING — cached, auto-invalidates on file change
# =====================================================

# Use the directory where the script is run from (your data folder)
# If CSVs are in a different folder, set DATA_DIR manually e.g.:
# DATA_DIR = "/home/shubham/Documents/geothon_2"
DATA_DIR = os.getcwd()

def file_mtime(path):
    try:
        return os.path.getmtime(path)
    except FileNotFoundError:
        return 0

@st.cache_data(ttl=300)   # re-check every 5 minutes
def load_data():
    files = {
        "risk":     os.path.join(DATA_DIR, "final_risk_scores.csv"),
        "anomaly":  os.path.join(DATA_DIR, "lake_risk_output.csv"),
        "exposure": os.path.join(DATA_DIR, "agricultural_exposure.csv"),
        "lakes":    os.path.join(DATA_DIR, "filtered_glacial_lakes.geojson"),
        "corridors":os.path.join(DATA_DIR, "flood_corridors.geojson"),
        "riskmap":  os.path.join(DATA_DIR, "final_risk_map.geojson"),
    }

    data = {}

    # Required files
    for key in ["risk", "anomaly", "exposure"]:
        path = files[key]
        if os.path.exists(path):
            data[key] = pd.read_csv(path)
        else:
            data[key] = None

    # Optional spatial files
    for key in ["lakes", "corridors", "riskmap"]:
        path = files[key]
        if os.path.exists(path):
            try:
                data[key] = gpd.read_file(path)
            except Exception:
                data[key] = None
        else:
            data[key] = None

    # Last updated = most recent file modification
    data["last_updated"] = max(file_mtime(p) for p in files.values())

    return data

# =====================================================
# HELPERS
# =====================================================

TIER_COLORS = {
    "CRITICAL": "#e74c3c",
    "High":     "#e67e22",
    "Moderate": "#f1c40f",
    "Low":      "#2ecc71"
}

def tier_badge(tier):
    color = TIER_COLORS.get(tier, "#bdc3c7")
    return f'<span style="color:{color};font-weight:bold">{tier}</span>'

def format_last_updated(ts):
    if ts == 0:
        return "Never"
    return datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M")

# =====================================================
# SIDEBAR
# =====================================================

with st.sidebar:
    st.image("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/100px-Flag_of_Nepal.svg.png",
             width=50)
    st.title("🏔️ GLOF Monitor")
    st.caption("Nepal Himalaya — Koshi / Gandaki / Karnali")

    st.divider()

    data = load_data()
    last_upd = format_last_updated(data["last_updated"])
    st.metric("Last Pipeline Run", last_upd)

    if st.button("🔄 Refresh Data"):
        st.cache_data.clear()
        st.rerun()

    st.divider()

    # Filters
    st.subheader("Filters")
    if data["risk"] is not None:
        df_risk = data["risk"]
        basins  = ["All"] + sorted(df_risk["Basin"].dropna().unique().tolist())
        sel_basin = st.selectbox("Basin", basins)
        sel_tiers = st.multiselect(
            "Risk Tier",
            ["CRITICAL", "High", "Moderate", "Low"],
            default=["CRITICAL", "High", "Moderate", "Low"]
        )
        top_n = st.slider("Show top N lakes", 5, 47, 10)
    else:
        st.warning("⚠️ Run pipeline phases 1–7 first to generate data files.")
        st.info(f"Looking for files in: {DATA_DIR}")
        st.info("Expected files: final_risk_scores.csv, lake_risk_output.csv, agricultural_exposure.csv")
        st.stop()

    st.divider()
    st.caption("S1 revisit: 6–12 days\nData: ICIMOD 2015 + GEE")

# =====================================================
# FILTER DATA
# =====================================================

df = data["risk"].copy()
if "rank" in df.columns:
    df = df.set_index("rank") if df.index.name != "rank" else df

if sel_basin != "All":
    df = df[df["Basin"] == sel_basin]

df = df[df["risk_tier"].isin(sel_tiers)]
df_top = df.sort_values("final_risk", ascending=False).head(top_n)

# =====================================================
# HEADER
# =====================================================

st.title("🏔️ GLOF Risk Intelligence Dashboard")
st.caption(f"Nepal Himalaya · Sentinel-1 SAR Monitoring · Updated: {last_upd}")

# =====================================================
# KPI ROW
# =====================================================

col1, col2, col3, col4, col5 = st.columns(5)

total_lakes    = len(data["risk"])
critical_count = len(data["risk"][data["risk"]["risk_tier"] == "CRITICAL"])
high_count     = len(data["risk"][data["risk"]["risk_tier"] == "High"])
top_risk_lake  = data["risk"].sort_values("final_risk", ascending=False).iloc[0]
total_crop_usd = data["exposure"]["crop_value_usd"].sum() if data["exposure"] is not None else 0

with col1:
    st.metric("Monitored Lakes", total_lakes)
with col2:
    st.metric("🔴 Critical", critical_count,
              delta=None if critical_count == 0 else f"{critical_count} lakes")
with col3:
    st.metric("🟠 High Risk", high_count)
with col4:
    st.metric("Top Risk Lake",
              top_risk_lake["GL_ID"][-10:],
              f"Score: {top_risk_lake['final_risk']:.3f}")
with col5:
    st.metric("Crop Value at Risk",
              f"${total_crop_usd/1e6:.1f}M" if total_crop_usd > 1e6
              else f"${total_crop_usd:,.0f}")

st.divider()

# =====================================================
# MAIN LAYOUT — map left, charts right
# =====================================================

map_col, chart_col = st.columns([3, 2])

# ── MAP ──
with map_col:
    st.subheader("🗺️ Lake Risk Map")

    m = folium.Map(
        location=[28.0, 86.5],
        zoom_start=7,
        tiles="CartoDB dark_matter"
    )

    # Plot all monitored lakes
    if data["lakes"] is not None:
        lakes_gdf = data["lakes"]
        risk_lookup = dict(zip(
            data["risk"]["GL_ID"],
            zip(data["risk"]["final_risk"],
                data["risk"]["risk_tier"])
        ))

        for _, row in lakes_gdf.iterrows():
            gl_id   = row["GL_ID"]
            info    = risk_lookup.get(gl_id, (0, "Low"))
            score   = info[0]
            tier    = info[1]
            color   = TIER_COLORS.get(tier, "#2ecc71")
            centroid = row.geometry.centroid

            folium.CircleMarker(
                location = [centroid.y, centroid.x],
                radius   = max(4, score * 12),
                color    = color,
                fill     = True,
                fill_color   = color,
                fill_opacity = 0.75,
                popup = folium.Popup(
                    f"<b>{gl_id}</b><br>"
                    f"Risk: <b>{tier}</b><br>"
                    f"Score: {score:.3f}<br>"
                    f"Basin: {row.get('Basin','')}",
                    max_width=200
                ),
                tooltip = f"{gl_id[-10:]} | {tier}"
            ).add_to(m)

    # Draw flood corridors for top-5
    if data["riskmap"] is not None:
        for _, row in data["riskmap"].iterrows():
            tier  = row.get("risk_tier", "Low")
            color = TIER_COLORS.get(tier, "#2ecc71")
            try:
                folium.GeoJson(
                    row.geometry.__geo_interface__,
                    style_function=lambda x, c=color: {
                        "fillColor": c,
                        "color":     c,
                        "weight":    1,
                        "fillOpacity": 0.25
                    },
                    tooltip=f"Corridor: {row['GL_ID'][-10:]}"
                ).add_to(m)
            except Exception:
                pass

    # Legend
    legend_html = """
    <div style="position:fixed;bottom:30px;left:30px;z-index:1000;
                background:#1a2634;padding:10px;border-radius:8px;
                border:1px solid #2c3e50;color:white;font-size:12px;">
    <b>Risk Level</b><br>
    <span style="color:#e74c3c">●</span> Critical<br>
    <span style="color:#e67e22">●</span> High<br>
    <span style="color:#f1c40f">●</span> Moderate<br>
    <span style="color:#2ecc71">●</span> Low<br>
    <i style="font-size:10px">Circle size = risk score</i>
    </div>"""
    m.get_root().html.add_child(folium.Element(legend_html))

    st_folium(m, width=700, height=500, returned_objects=[])

# ── CHARTS ──
with chart_col:
    st.subheader("📊 Risk Analysis")

    tab1, tab2, tab3 = st.tabs(["Rankings", "Components", "Seasonal"])

    with tab1:
        fig = px.bar(
            df_top.reset_index().sort_values("final_risk"),
            x="final_risk", y="GL_ID",
            orientation="h",
            color="risk_tier",
            color_discrete_map=TIER_COLORS,
            labels={"final_risk": "Risk Score", "GL_ID": "Lake"},
            template="plotly_dark",
            height=400
        )
        fig.update_layout(
            paper_bgcolor="#1a2634",
            plot_bgcolor="#1a2634",
            showlegend=True
        )
        st.plotly_chart(fig, width='stretch')

    with tab2:
        top5 = data["risk"].sort_values("final_risk", ascending=False).head(5)
        fig2 = go.Figure()
        fig2.add_trace(go.Bar(
            name="Anomaly (0.45)",
            x=top5["GL_ID"].str[-10:],
            y=top5["anomaly_norm"],
            marker_color="#3498db"
        ))
        fig2.add_trace(go.Bar(
            name="Exposure (0.35)",
            x=top5["GL_ID"].str[-10:],
            y=top5["exposure_norm"],
            marker_color="#27ae60"
        ))
        fig2.add_trace(go.Bar(
            name="Seasonal (0.20)",
            x=top5["GL_ID"].str[-10:],
            y=top5["seasonal_norm"],
            marker_color="#f39c12"
        ))
        fig2.update_layout(
            barmode="group",
            template="plotly_dark",
            paper_bgcolor="#1a2634",
            plot_bgcolor="#1a2634",
            height=400,
            legend=dict(orientation="h", y=-0.2)
        )
        st.plotly_chart(fig2, width='stretch')

    with tab3:
        # Seasonal vulnerability wheel
        months = ["Jan","Feb","Mar","Apr","May","Jun",
                  "Jul","Aug","Sep","Oct","Nov","Dec"]
        crop_cal = {
            "Rice":  [0.2,0.2,0.3,0.4,0.5,0.7,0.8,0.9,1.0,1.0,0.7,0.2],
            "Maize": [0.2,0.2,0.4,0.6,0.8,1.0,1.0,0.9,0.5,0.3,0.2,0.2],
            "Wheat": [0.7,0.8,1.0,1.0,0.5,0.2,0.2,0.2,0.2,0.3,0.4,0.6]
        }
        fig3 = go.Figure()
        colors3 = {"Rice":"#3498db","Maize":"#f39c12","Wheat":"#e74c3c"}
        for crop, vals in crop_cal.items():
            fig3.add_trace(go.Scatterpolar(
                r=vals + [vals[0]],
                theta=months + [months[0]],
                fill="toself",
                name=crop,
                line_color=colors3[crop],
                fillcolor=colors3[crop],
                opacity=0.3
            ))
        fig3.update_layout(
            polar=dict(
                radialaxis=dict(visible=True, range=[0,1],
                                color="white", gridcolor="#2c3e50"),
                angularaxis=dict(color="white", gridcolor="#2c3e50"),
                bgcolor="#1a2634"
            ),
            paper_bgcolor="#1a2634",
            template="plotly_dark",
            height=380,
            legend=dict(font=dict(color="white"))
        )
        st.plotly_chart(fig3, width='stretch')

# =====================================================
# FULL RISK TABLE
# =====================================================

st.divider()
st.subheader("📋 Full Risk Table")

display_cols = ["GL_ID","Basin","Sub_Basin","z_score","cropland_km2",
                "final_risk","risk_tier","crop_value_usd"]
available    = [c for c in display_cols if c in df_top.columns]

st.dataframe(
    df_top[available].reset_index(drop=True).style
    .background_gradient(subset=["final_risk"], cmap="RdYlGn_r")
    .format({"final_risk":"{:.3f}", "z_score":"{:.2f}",
             "cropland_km2":"{:.3f}", "crop_value_usd":"${:,.0f}"}),
    width='stretch',
    height=350
)

# =====================================================
# DOWNLOAD
# =====================================================

st.divider()
col_dl1, col_dl2 = st.columns(2)

with col_dl1:
    csv = data["risk"].to_csv(index=False)
    st.download_button(
        "⬇️ Download Risk Scores CSV",
        data=csv,
        file_name="glof_risk_scores.csv",
        mime="text/csv"
    )

with col_dl2:
    if data["riskmap"] is not None:
        geojson_str = data["riskmap"].to_json()
        st.download_button(
            "⬇️ Download Risk Map GeoJSON",
            data=geojson_str,
            file_name="glof_risk_map.geojson",
            mime="application/json"
        )

st.caption("Built with Sentinel-1 SAR · NASADEM · ESA WorldCover · ICIMOD Glacial Lake Inventory")